version: "3"

services:
  db:
    image: postgres:latest
    restart: always
    environment:
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
    ports: 
      - 5432:5432

  backend:
    image: weworld-backend:v1.1.1
    environment:
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
      - POSTGRES_HOST=db
    ports:
      - 3000:3000
    tty: true
    depends_on:
      - db

  frontend:
    image: weworld-frontend:latest
    ports:
      - 8080:8080
    depends_on:
      - backend


