version: "3"

services:
  db:
    image: postgres:latest
    restart: always
    # set env variables
    environment:
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
    ports: 
      - 5432:5432

  backend:
    # image: democratic-backend:v0.0.1
    image: test-backend:v0.0.3
    environment:
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
      - POSTGRES_HOST=db
    ports:
      - 3000:3000
    tty: true
    depends_on:
      - db

  frontend:
    image: democratic-frontend:v0.0.4
    ports:
      # - 8080:8080
      - 80:80
    depends_on:
      - backend


